# Generated by Django 4.2.20 on 2025-03-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanCalculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_term', models.IntegerField()),
                ('max_term', models.IntegerField()),
                ('interest_ratte', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanCalculator.bank')),
            ],
        ),
    ]
