# Generated by Django 4.2.20 on 2025-03-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanCalculator', '0002_bank_loanproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanproduct',
            old_name='interest_ratte',
            new_name='interest_rate',
        ),
    ]
