# Generated by Django 4.2.20 on 2025-03-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanCalculator', '0003_rename_interest_ratte_loanproduct_interest_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=8)),
                ('holiday', models.DateField()),
            ],
        ),
    ]
