# Generated by Django 4.2.20 on 2025-03-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanCalculator', '0004_holidays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidays',
            old_name='year',
            new_name='yearMonth',
        ),
    ]
